package com.example.worldcurrencyrate.ui.theme

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val EXTRA_LARGE_PADDING = 40.dp
val MEDIUM_LARGE_PADDING = 32.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val EXTRA_SMALL_PADDING = 6.dp

val CURRENCY_NAME_TEXT_SIZE = 22.sp
val SECONDARY_TEXT_SIZE = 12.sp
val SECONDARY_WIDGET_TEXT_SIZE = 10.sp
val WIDGET_MAIN_CURRENCY_TEXT_SIZE = 13.sp
val TEXT_MENU_FONT_SIZE = 12.sp
val TEXT_SYMBOLS_MENU_FONT_SIZE = 18.sp
val CURRENCY_ITEM_MAIN_TEXT_FONT_SIZE = 21.sp

val MORE_ITEMS_ICON_SIZE = 20.dp
val COUNTRY_FLAG_ICON_SIZE = 55.dp
val MENU_ICON_SIZE = 21.dp
val CURRENCY_LIST_ITEM_MENU_ICON_SIZE = 35.dp
val MAIN_CURRENCY_WIDGET_ICON_SIZE = 40.dp
val CALENDAR_ICON_SIZE = 30.dp
val PROGRESS_BAR_SIZE = 18.dp

val SNACK_BAR_ANIMATION_SIZE = 50.dp

val CURRENCY_LIST_ITEM_MAIN_TEXT_WIDTH = 130.dp

val MENU_CORNER_RADIUS = 12.dp
val ADD_CURRENCY_BUTTON_CORNER_RADIUS = 8.dp

val SNACK_BAR_ELEVATION = 4.dp
