package com.example.worldcurrencyrate.utils

data class Symbols(
    val AED: String = "United Arab Emirates Dirham",
    val AFN: String = "Afghan Afghani",
    val ALL: String = "Albanian Lek",
    val AMD: String = "Armenian Dram",
    val ANG: String = "Netherlands Antillean Guilder",
    val AOA: String = "Angolan Kwanza",
    val ARS: String = "Argentine Peso",
    val AUD: String = "Australian Dollar",
    val AWG: String = "Aruban Florin",
    val AZN: String = "Azerbaijani Manat",
    val BAM: String = "Bosnia - Herzegovina Convertible Mark",
    val BBD: String = "Barbadian Dollar",
    val BDT: String = "Bangladeshi Taka",
    val BGN: String = "Bulgarian Lev",
    val BHD: String = "Bahraini Dinar",
    val BIF: String = "Burundian Franc",
    val BMD: String = "Bermudan Dollar",
    val BND: String = "Brunei Dollar",
    val BOB: String = "Bolivian Boliviano",
    val BRL: String = "Brazilian Real",
    val BSD: String = "Bahamian Dollar",
    val BTN: String = "Bhutanese Ngultrum",
    val BWP: String = "Botswanan Pula",
    val BYR: String = "Belarusian Ruble",
    val BZD: String = "Belize Dollar",
    val CAD: String = "Canadian Dollar",
    val CDF: String = "Congolese Franc",
    val CHF: String = "Swiss Franc",
    val CLP: String = "Chilean Peso",
    val CNY: String = "Chinese Yuan",
    val COP: String = "Colombian Peso",
    val CRC: String = "Costa Rican Col\u00f3n ",
    val CUP: String = " Cuban Peso ",
    val CVE: String = " Cape Verdean Escudo ",
    val CZK: String = " Czech Republic Koruna ",
    val DJF: String = " Djiboutian Franc ",
    val DKK: String = " Danish Krone ",
    val DOP: String = " Dominican Peso ",
    val DZD: String = " Algerian Dinar ",
    val EGP: String = " Egyptian Pound ",
    val ERN: String = " Eritrean Nakfa ",
    val ETB: String = " Ethiopian Birr ",
    val EUR: String = " Euro ",
    val FJD: String = " Fijian Dollar ",
    val FKP: String = " Falkland Islands Pound ",
    val GBP: String = " British Pound Sterling ",
    val GEL: String = " Georgian Lari ",
    val GGP: String = " Guernsey Pound ",
    val GHS: String = " Ghanaian Cedi ",
    val GIP: String = " Gibraltar Pound ",
    val GMD: String = " Gambian Dalasi ",
    val GNF: String = " Guinean Franc ",
    val GTQ: String = " Guatemalan Quetzal ",
    val HKD: String = " Hong Kong Dollar ",
    val HNL: String = " Honduran Lempira ",
    val HRK: String = " Croatian Kuna ",
    val HTG: String = " Haitian Gourde ",
    val HUF: String = " Hungarian Forint ",
    val IDR: String = " Indonesian Rupiah ",
    val ILS: String = " Israeli New Sheqel ",
    val IMP: String = " Manx pound ",
    val INR: String = " Indian Rupee ",
    val IQD: String = " Iraqi Dinar ",
    val IRR: String = " Iranian Rial ",
    val ISK: String = " Icelandic Kr\u00f3na ",
    val JEP: String = " Jersey Pound ",
    val JMD: String = " Jamaican Dollar ",
    val JOD: String = " Jordanian Dinar ",
    val JPY: String = " Japanese Yen ",
    val KES: String = " Kenyan Shilling ",
    val KGS: String = " Kyrgystani Som ",
    val KHR: String = " Cambodian Riel ",
    val KMF: String = " Comorian Franc ",
    val KPW: String = " North Korean Won ",
    val KRW: String = " South Korean Won ",
    val KWD: String = " Kuwaiti Dinar ",
    val KYD: String = " Cayman Islands Dollar ",
    val KZT: String = " Kazakhstani Tenge ",
    val LAK: String = " Laotian Kip",
    val LBP: String = " Lebanese Pound",
    val LKR: String = " Sri Lankan Rupee",
    val LRD: String = " Liberian Dollar",
    val LSL: String = " Lesotho Loti",
    val LTL: String = " Lithuanian Litas",
    val LVL: String = " Latvian Lats",
    val LYD: String = " Libyan Dinar",
    val MAD: String = " Moroccan Dirham ",
    val MDL: String = " Moldovan Leu ",
    val MGA: String = " Malagasy Ariary ",
    val MKD: String = " Macedonian Denar ",
    val MMK: String = " Myanma Kyat ",
    val MNT: String = " Mongolian Tugrik ",
    val MOP: String = " Macanese Pataca ",
    val MRO: String = " Mauritanian Ouguiya ",
    val MUR: String = " Mauritian Rupee ",
    val MVR: String = " Maldivian Rufiyaa ",
    val MWK: String = " Malawian Kwacha ",
    val MXN: String = " Mexican Peso ",
    val MYR: String = " Malaysian Ringgit ",
    val MZN: String = " Mozambican Metical ",
    val NAD: String = " Namibian Dollar ",
    val NGN: String = " Nigerian Naira ",
    val NIO: String = " Nicaraguan C\u00f3rdoba ",
    val NOK: String = " Norwegian Krone ",
    val NPR: String = " Nepalese Rupee ",
    val NZD: String = " New Zealand Dollar ",
    val OMR: String = " Omani Rial ",
    val PAB: String = " Panamanian Balboa ",
    val PEN: String = " Peruvian Nuevo Sol ",
    val PGK: String = " Papua New Guinean Kina ",
    val PHP: String = " Philippine Peso ",
    val PKR: String = " Pakistani Rupee ",
    val PLN: String = " Polish Zloty ",
    val PYG: String = " Paraguayan Guarani ",
    val QAR: String = " Qatari Rial ",
    val RON: String = " Romanian Leu ",
    val RSD: String = " Serbian Dinar ",
    val RUB: String = " Russian Ruble ",
    val RWF: String = " Rwandan Franc ",
    val SAR: String = " Saudi Riyal ",
    val SBD: String = " Solomon Islands Dollar ",
    val SCR: String = " Seychellois Rupee ",
    val SDG: String = " Sudanese Pound ",
    val SEK: String = " Swedish Krona ",
    val SGD: String = " Singapore Dollar ",
    val SLE: String = " Sierra Leonean Leone ",
    val SOS: String = " Somali Shilling ",
    val SRD: String = " Surinamese Dollar ",
    val STD: String = " S\u00e3o Tom\u00e9 and Pr\u00edncipe Dobra ",
    val SYP: String = " Syrian Pound ",
    val SZL: String = " Swazi Lilangeni ",
    val THB: String = " Thai Baht ",
    val TJS: String = " Tajikistani Somoni ",
    val TMT: String = " Turkmenistani Manat ",
    val TND: String = " Tunisian Dinar ",
    val TOP: String = " Tongan Pa\u02bbanga ",
    val TTD: String = " Trinidad and Tobago Dollar ",
    val TWD: String = " New Taiwan Dollar ",
    val TZS: String = " Tanzanian Shilling ",
    val UAH: String = " Ukrainian Hryvnia ",
    val UGX: String = " Ugandan Shilling ",
    val USD: String = " United States Dollar ",
    val UYU: String = " Uruguayan Peso ",
    val UZS: String = " Uzbekistan Som ",
    val VEF: String = " Venezuelan Bol\u00edvar Fuerte ",
    val VES: String = " Sovereign Bolivar ",
    val VND: String = " Vietnamese Dong ",
    val VUV: String = " Vanuatu Vatu ",
    val WST: String = " Samoan Tala ",
    val XPF: String = " CFP Franc ",
    val YER: String = " Yemeni Rial ",
    val ZMK: String = " Zambian Kwacha (pre-2013) ",
    val ZMW: String = " Zambian Kwacha ",
    val ZWL: String = " Zimbabwean Dollar"
) {

    fun toMap(): Map<String, String> {
        return mapOf(
            "AED" to "United Arab Emirates Dirham",
            "AFN" to "Afghan Afghani",
            "ALL" to "Albanian Lek",
            "AMD" to "Armenian Dram",
            "ANG" to "Netherlands Antillean Guilder",
            "AOA" to "Angolan Kwanza",
            "ARS" to "Argentine Peso",
            "AUD" to "Australian Dollar",
            "AWG" to "Aruban Florin",
            "AZN" to "Azerbaijani Manat",
            "BAM" to "Bosnia - Herzegovina Convertible Mark",
            "BBD" to "Barbadian Dollar",
            "BDT" to "Bangladeshi Taka",
            "BGN" to "Bulgarian Lev",
            "BHD" to "Bahraini Dinar",
            "BIF" to "Burundian Franc",
            "BMD" to "Bermudan Dollar",
            "BND" to "Brunei Dollar",
            "BOB" to "Bolivian Boliviano",
            "BRL" to "Brazilian Real",
            "BSD" to "Bahamian Dollar",
            "BTN" to "Bhutanese Ngultrum",
            "BWP" to "Botswanan Pula",
            "BYR" to "Belarusian Ruble",
            "BZD" to "Belize Dollar",
            "CAD" to "Canadian Dollar",
            "CDF" to "Congolese Franc",
            "CHF" to "Swiss Franc",
            "CLP" to "Chilean Peso",
            "CNY" to "Chinese Yuan",
            "COP" to "Colombian Peso",
            "CRC" to "Costa Rican Col\u00f3n ",
            "CUP" to " Cuban Peso ",
            "CVE" to " Cape Verdean Escudo ",
            "CZK" to " Czech Republic Koruna ",
            "DJF" to " Djiboutian Franc ",
            "DKK" to " Danish Krone ",
            "DOP" to " Dominican Peso ",
            "DZD" to " Algerian Dinar ",
            "EGP" to " Egyptian Pound ",
            "ERN" to " Eritrean Nakfa ",
            "ETB" to " Ethiopian Birr ",
            "EUR" to " Euro ",
            "FJD" to " Fijian Dollar ",
            "FKP" to " Falkland Islands Pound ",
            "GBP" to " British Pound Sterling ",
            "GEL" to " Georgian Lari ",
            "GGP" to " Guernsey Pound ",
            "GHS" to " Ghanaian Cedi ",
            "GIP" to " Gibraltar Pound ",
            "GMD" to " Gambian Dalasi ",
            "GNF" to " Guinean Franc ",
            "GTQ" to " Guatemalan Quetzal ",
            "HKD" to " Hong Kong Dollar ",
            "HNL" to " Honduran Lempira ",
            "HRK" to " Croatian Kuna ",
            "HTG" to " Haitian Gourde ",
            "HUF" to " Hungarian Forint ",
            "IDR" to " Indonesian Rupiah ",
            "ILS" to " Israeli New Sheqel ",
            "IMP" to " Manx pound ",
            "INR" to " Indian Rupee ",
            "IQD" to " Iraqi Dinar ",
            "IRR" to " Iranian Rial ",
            "ISK" to " Icelandic Kr\u00f3na ",
            "JEP" to " Jersey Pound ",
            "JMD" to " Jamaican Dollar ",
            "JOD" to " Jordanian Dinar ",
            "JPY" to " Japanese Yen ",
            "KES" to " Kenyan Shilling ",
            "KGS" to " Kyrgystani Som ",
            "KHR" to " Cambodian Riel ",
            "KMF" to " Comorian Franc ",
            "KPW" to " North Korean Won ",
            "KRW" to " South Korean Won ",
            "KWD" to " Kuwaiti Dinar ",
            "KYD" to " Cayman Islands Dollar ",
            "KZT" to " Kazakhstani Tenge ",
            "LAK" to " Laotian Kip",
            "LBP" to " Lebanese Pound",
            "LKR" to " Sri Lankan Rupee",
            "LRD" to " Liberian Dollar",
            "LSL" to " Lesotho Loti",
            "LTL" to " Lithuanian Litas",
            "LVL" to " Latvian Lats",
            "LYD" to " Libyan Dinar",
            "MAD" to " Moroccan Dirham ",
            "MDL" to " Moldovan Leu ",
            "MGA" to " Malagasy Ariary ",
            "MKD" to " Macedonian Denar ",
            "MMK" to " Myanma Kyat ",
            "MNT" to " Mongolian Tugrik ",
            "MOP" to " Macanese Pataca ",
            "MRO" to " Mauritanian Ouguiya ",
            "MUR" to " Mauritian Rupee ",
            "MVR" to " Maldivian Rufiyaa ",
            "MWK" to " Malawian Kwacha ",
            "MXN" to " Mexican Peso ",
            "MYR" to " Malaysian Ringgit ",
            "MZN" to " Mozambican Metical ",
            "NAD" to " Namibian Dollar ",
            "NGN" to " Nigerian Naira ",
            "NIO" to " Nicaraguan C\u00f3rdoba ",
            "NOK" to " Norwegian Krone ",
            "NPR" to " Nepalese Rupee ",
            "NZD" to " New Zealand Dollar ",
            "OMR" to " Omani Rial ",
            "PAB" to " Panamanian Balboa ",
            "PEN" to " Peruvian Nuevo Sol ",
            "PGK" to " Papua New Guinean Kina ",
            "PHP" to " Philippine Peso ",
            "PKR" to " Pakistani Rupee ",
            "PLN" to " Polish Zloty ",
            "PYG" to " Paraguayan Guarani ",
            "QAR" to " Qatari Rial ",
            "RON" to " Romanian Leu ",
            "RSD" to " Serbian Dinar ",
            "RUB" to " Russian Ruble ",
            "RWF" to " Rwandan Franc ",
            "SAR" to " Saudi Riyal ",
            "SBD" to " Solomon Islands Dollar ",
            "SCR" to " Seychellois Rupee ",
            "SDG" to " Sudanese Pound ",
            "SEK" to " Swedish Krona ",
            "SGD" to " Singapore Dollar ",
            "SLE" to " Sierra Leonean Leone ",
            "SOS" to " Somali Shilling ",
            "SRD" to " Surinamese Dollar ",
            "STD" to " S\u00e3o Tom\u00e9 and Pr\u00edncipe Dobra ",
            "SYP" to " Syrian Pound ",
            "SZL" to " Swazi Lilangeni ",
            "THB" to " Thai Baht ",
            "TJS" to " Tajikistani Somoni ",
            "TMT" to " Turkmenistani Manat ",
            "TND" to " Tunisian Dinar ",
            "TOP" to " Tongan Pa\u02bbanga ",
            "TTD" to " Trinidad and Tobago Dollar ",
            "TWD" to " New Taiwan Dollar ",
            "TZS" to " Tanzanian Shilling ",
            "UAH" to " Ukrainian Hryvnia ",
            "UGX" to " Ugandan Shilling ",
            "USD" to " United States Dollar ",
            "UYU" to " Uruguayan Peso ",
            "UZS" to " Uzbekistan Som ",
            "VEF" to " Venezuelan Bol\u00edvar Fuerte ",
            "VES" to " Sovereign Bolivar ",
            "VND" to " Vietnamese Dong ",
            "VUV" to " Vanuatu Vatu ",
            "WST" to " Samoan Tala ",
            "XPF" to " CFP Franc ",
            "YER" to " Yemeni Rial ",
            "ZMK" to " Zambian Kwacha (pre-2013) ",
            "ZMW" to " Zambian Kwacha ",
            "ZWL" to " Zimbabwean Dollar"
        )
    }

    fun toStringWithSeparator(
        separator: String = ", "
    ): String {
        val currencyList = listOf(
            "AED",
            "AFN",
            "ALL",
            "AMD",
            "ANG",
            "AOA",
            "ARS",
            "AUD",
            "AWG",
            "AZN",
            "BAM",
            "BBD",
            "BDT",
            "BGN",
            "BHD",
            "BIF",
            "BMD",
            "BND",
            "BOB",
            "BRL",
            "BSD",
            "BTN",
            "BWP",
            "BYR",
            "BZD",
            "CAD",
            "CDF",
            "CHF",
            "CLP",
            "CNY",
            "COP",
            "CRC",
            "CUP",
            "CVE",
            "CZK",
            "DJF",
            "DKK",
            "DOP",
            "DZD",
            "EGP",
            "ERN",
            "ETB",
            "EUR",
            "FJD",
            "FKP",
            "GBP",
            "GEL",
            "GGP",
            "GHS",
            "GIP",
            "GMD",
            "GNF",
            "GTQ",
            "HKD",
            "HNL",
            "HRK",
            "HTG",
            "HUF",
            "IDR",
            "ILS",
            "IMP",
            "INR",
            "IQD",
            "IRR",
            "ISK",
            "JEP",
            "JMD",
            "JOD",
            "JPY",
            "KES",
            "KGS",
            "KHR",
            "KMF",
            "KPW",
            "KRW",
            "KWD",
            "KYD",
            "KZT",
            "LAK",
            "LBP",
            "LKR",
            "LRD",
            "LSL",
            "LTL",
            "LVL",
            "LYD",
            "MAD",
            "MDL",
            "MGA",
            "MKD",
            "MMK",
            "MNT",
            "MOP",
            "MRO",
            "MUR",
            "MVR",
            "MWK",
            "MXN",
            "MYR",
            "MZN",
            "NAD",
            "NGN",
            "NIO",
            "NOK",
            "NPR",
            "NZD",
            "OMR",
            "PAB",
            "PEN",
            "PGK",
            "PHP",
            "PKR",
            "PLN",
            "PYG",
            "QAR",
            "RON",
            "RSD",
            "RUB",
            "RWF",
            "SAR",
            "SBD",
            "SCR",
            "SDG",
            "SEK",
            "SGD",
            "SLE",
            "SOS",
            "SRD",
            "STD",
            "SYP",
            "SZL",
            "THB",
            "TJS",
            "TMT",
            "TND",
            "TOP",
            "TTD",
            "TWD",
            "TZS",
            "UAH",
            "UGX",
            "USD",
            "UYU",
            "UZS",
            "VEF",
            "VES",
            "VND",
            "VUV",
            "WST",
            "XPF",
            "YER",
            "ZMK",
            "ZMW",
            "ZWL",
        )
        return currencyList.joinToString(separator = separator)
    }

}
